### ISSUE TITLE
Using mailgun.com to send emails

### ISSUE THREAD

**Issue by ccauet** [pep-dortmund/personalized-emails#1]
I suggest using http://www.mailgun.com to send messages.

Features: 
- use own domain
- 10k Emails free/month. 
- All the tech stuff: SPF, DKIM, etc...

It is either possible to use der RESTful API or an SMTP server to send mail. Besides sending mails, there is a lot of room for future improvements as automated receiving and tracking of mails.

**Comment by maxnoe** [comment]
This looks pretty awesome

**Comment by maxnoe** [comment]
This now has a `mailgun` backend

Use this config:

```
[mailgun]
domain: <domain>
authkey: <key>
```

And then

```
jinjamails template.md recipients.json --backend=mailgun
```
